//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppResoursces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppResoursces.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this page.
        /// </summary>
        public static string AccessDeniedMessage {
            get {
                return ResourceManager.GetString("AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter carrier name.
        /// </summary>
        public static string CarrierNameRequired {
            get {
                return ResourceManager.GetString("CarrierNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes Discarded.
        /// </summary>
        public static string ChangesDiscarded {
            get {
                return ResourceManager.GetString("ChangesDiscarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission must be between 0 and 100.
        /// </summary>
        public static string CommissionRange {
            get {
                return ResourceManager.GetString("CommissionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission is required.
        /// </summary>
        public static string CommissionRequired {
            get {
                return ResourceManager.GetString("CommissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to proceed?.
        /// </summary>
        public static string ConfirmationPrompt {
            get {
                return ResourceManager.GetString("ConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a country.
        /// </summary>
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed. Please try again..
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the item. Please try again.
        /// </summary>
        public static string DeleteFailedMessage {
            get {
                return ResourceManager.GetString("DeleteFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Failed.
        /// </summary>
        public static string DeleteFailedTitle {
            get {
                return ResourceManager.GetString("DeleteFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item has been deleted successfully.
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string DeleteSuccessTitle {
            get {
                return ResourceManager.GetString("DeleteSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery date is required.
        /// </summary>
        public static string DeliveryDateRequired {
            get {
                return ResourceManager.GetString("DeliveryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone Number.
        /// </summary>
        public static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor Is Required.
        /// </summary>
        public static string FactorIsRequired {
            get {
                return ResourceManager.GetString("FactorIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range must be between 0.25 and 10.
        /// </summary>
        public static string FactorRange {
            get {
                return ResourceManager.GetString("FactorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter first name.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package height must be greater than 0.
        /// </summary>
        public static string HeightRange {
            get {
                return ResourceManager.GetString("HeightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package height is required.
        /// </summary>
        public static string HeightRequired {
            get {
                return ResourceManager.GetString("HeightRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometer rate must be greater than 0.
        /// </summary>
        public static string KiloMeterRateRange {
            get {
                return ResourceManager.GetString("KiloMeterRateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometer rate is required.
        /// </summary>
        public static string KiloMeterRateRequired {
            get {
                return ResourceManager.GetString("KiloMeterRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram rate must be greater than 0.
        /// </summary>
        public static string KilooGramRateRange {
            get {
                return ResourceManager.GetString("KilooGramRateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram rate is required.
        /// </summary>
        public static string KilooGramRateRequired {
            get {
                return ResourceManager.GetString("KilooGramRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter last name.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package length must be greater than 0.
        /// </summary>
        public static string LengthRange {
            get {
                return ResourceManager.GetString("LengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package length is required.
        /// </summary>
        public static string LengthRequired {
            get {
                return ResourceManager.GetString("LengthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in successfully.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out successfully.
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Arabic method name.
        /// </summary>
        public static string MethodAnameRequired {
            get {
                return ResourceManager.GetString("MethodAnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter English method name.
        /// </summary>
        public static string MethodEnameRequired {
            get {
                return ResourceManager.GetString("MethodEnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Arabic name..
        /// </summary>
        public static string NameArRequired {
            get {
                return ResourceManager.GetString("NameArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter English name.
        /// </summary>
        public static string NameEnRequired {
            get {
                return ResourceManager.GetString("NameEnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should be between 5 and 100 characters..
        /// </summary>
        public static string NameLength {
            get {
                return ResourceManager.GetString("NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of kilometers must be greater than 0.
        /// </summary>
        public static string NumberOfKiloMetersRange {
            get {
                return ResourceManager.GetString("NumberOfKiloMetersRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of kilometers is required.
        /// </summary>
        public static string NumberOfKiloMetersRequired {
            get {
                return ResourceManager.GetString("NumberOfKiloMetersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter package name.
        /// </summary>
        public static string PackageNameRequired {
            get {
                return ResourceManager.GetString("PackageNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package value must be greater than 0.
        /// </summary>
        public static string PackageValueRange {
            get {
                return ResourceManager.GetString("PackageValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package value is required.
        /// </summary>
        public static string PackageValueRequired {
            get {
                return ResourceManager.GetString("PackageValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 6 and 100 characters.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number.
        /// </summary>
        public static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver information is required.
        /// </summary>
        public static string ReceiverIdRequired {
            get {
                return ResourceManager.GetString("ReceiverIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Not Found.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed. Please try again..
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save data. Please try again.
        /// </summary>
        public static string SaveFailedMessage {
            get {
                return ResourceManager.GetString("SaveFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failed.
        /// </summary>
        public static string SaveFailedTitle {
            get {
                return ResourceManager.GetString("SaveFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data has been saved successfully.
        /// </summary>
        public static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender information is required.
        /// </summary>
        public static string SenderIdRequired {
            get {
                return ResourceManager.GetString("SenderIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired..
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment count must be greater than 0.
        /// </summary>
        public static string ShippimentCountRange {
            get {
                return ResourceManager.GetString("ShippimentCountRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment count is required.
        /// </summary>
        public static string ShippimentCountRequired {
            get {
                return ResourceManager.GetString("ShippimentCountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping date is required.
        /// </summary>
        public static string ShippingDateRequired {
            get {
                return ResourceManager.GetString("ShippingDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic name must not exceed 200 characters.
        /// </summary>
        public static string ShippingPackagingAnameMax {
            get {
                return ResourceManager.GetString("ShippingPackagingAnameMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic name is required.
        /// </summary>
        public static string ShippingPackagingAnameRequired {
            get {
                return ResourceManager.GetString("ShippingPackagingAnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name must not exceed 200 characters.
        /// </summary>
        public static string ShippingPackagingEnameMax {
            get {
                return ResourceManager.GetString("ShippingPackagingEnameMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name is required.
        /// </summary>
        public static string ShippingPackagingEnameRequired {
            get {
                return ResourceManager.GetString("ShippingPackagingEnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping rate must be greater than 0.
        /// </summary>
        public static string ShippingRateRange {
            get {
                return ResourceManager.GetString("ShippingRateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping rate is required.
        /// </summary>
        public static string ShippingRateRequired {
            get {
                return ResourceManager.GetString("ShippingRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping type must be selected.
        /// </summary>
        public static string ShippingTypeRequired {
            get {
                return ResourceManager.GetString("ShippingTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total weight must be greater than 0.
        /// </summary>
        public static string TotalWeightRange {
            get {
                return ResourceManager.GetString("TotalWeightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total weight is required..
        /// </summary>
        public static string TotalWeightRequired {
            get {
                return ResourceManager.GetString("TotalWeightRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Action.
        /// </summary>
        public static string UnauthorizedAction {
            get {
                return ResourceManager.GetString("UnauthorizedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed. Please try again..
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update data. Please try again.
        /// </summary>
        public static string UpdateFailedMessage {
            get {
                return ResourceManager.GetString("UpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed .
        /// </summary>
        public static string UpdateFailedTitle {
            get {
                return ResourceManager.GetString("UpdateFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully..
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data has been updated successfully..
        /// </summary>
        public static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string UpdateSuccessTitle {
            get {
                return ResourceManager.GetString("UpdateSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter username.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package width must be greater than 0.
        /// </summary>
        public static string WidthRange {
            get {
                return ResourceManager.GetString("WidthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package width is required.
        /// </summary>
        public static string WidthRequired {
            get {
                return ResourceManager.GetString("WidthRequired", resourceCulture);
            }
        }
    }
}
